spring:
  profiles:
    active: local_mysql

---
spring:
  config:
    activate:
      on-profile: local_h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/testdb
      username: sa
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: always # develop only use never

---
spring:
  config:
    activate:
      on-profile: local_mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springbatch
      username: local_rdb_master
      password: local_rdb
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always # develop only use never
    job:
      enabled: false #disable auto run job